/*-- QiOS ---------------------------------------------------------------------*
 *                                                                             *
 *	Copyright (C) 2017, 2018 Liew Tze Wei                                      *
 *                                                                             *
 * 	This file is part of the QiOS kernel, and is made available under the      *
 *  terms of The Unlicense (That means just do whatever you want with the code *
 *  base).                                                                     *
 * ****************************************************************************/
#include "idt.h"
#include "asm.h"
#include "func.h"
#include "gdt.h"
#include "interrupts.h"

#define PIC1 0x20 /* IO base address for master PIC */
#define PIC2 0xA0 /* IO base address for slave PIC */
#define PIC1_COMMAND PIC1
#define PIC1_DATA (PIC1 + 1)
#define PIC2_COMMAND PIC2
#define PIC2_DATA (PIC2 + 1)
#define PIC_EOI 0x20 /* End-of-interrupt command code */

idt_desc_t idt_descriptor;
idt_desc_tab_t idt[256];
uint32_t interrupt_handler_addresses[] = {
    interrupt_handler_0,
    interrupt_handler_1,
    interrupt_handler_2,
    interrupt_handler_3,
    interrupt_handler_4,
    interrupt_handler_5,
    interrupt_handler_6,
    interrupt_handler_7,
    interrupt_handler_8,
    interrupt_handler_9,
    interrupt_handler_10,
    interrupt_handler_11,
    interrupt_handler_12,
    interrupt_handler_13,
    interrupt_handler_14,
    interrupt_handler_15,
    interrupt_handler_16,
    interrupt_handler_17,
    interrupt_handler_18,
    interrupt_handler_19,
    interrupt_handler_20,
    interrupt_handler_21,
    interrupt_handler_22,
    interrupt_handler_23,
    interrupt_handler_24,
    interrupt_handler_25,
    interrupt_handler_26,
    interrupt_handler_27,
    interrupt_handler_28,
    interrupt_handler_29,
    interrupt_handler_30,
    interrupt_handler_31,
    interrupt_handler_32,
    interrupt_handler_33,
    interrupt_handler_34,
    interrupt_handler_35,
    interrupt_handler_36,
    interrupt_handler_37,
    interrupt_handler_38,
    interrupt_handler_39,
    interrupt_handler_40,
    interrupt_handler_41,
    interrupt_handler_42,
    interrupt_handler_43,
    interrupt_handler_44,
    interrupt_handler_45,
    interrupt_handler_46,
    interrupt_handler_47,
    interrupt_handler_48,
    interrupt_handler_49,
    interrupt_handler_50,
    interrupt_handler_51,
    interrupt_handler_52,
    interrupt_handler_53,
    interrupt_handler_54,
    interrupt_handler_55,
    interrupt_handler_56,
    interrupt_handler_57,
    interrupt_handler_58,
    interrupt_handler_59,
    interrupt_handler_60,
    interrupt_handler_61,
    interrupt_handler_62,
    interrupt_handler_63,
    interrupt_handler_64,
    interrupt_handler_65,
    interrupt_handler_66,
    interrupt_handler_67,
    interrupt_handler_68,
    interrupt_handler_69,
    interrupt_handler_70,
    interrupt_handler_71,
    interrupt_handler_72,
    interrupt_handler_73,
    interrupt_handler_74,
    interrupt_handler_75,
    interrupt_handler_76,
    interrupt_handler_77,
    interrupt_handler_78,
    interrupt_handler_79,
    interrupt_handler_80,
    interrupt_handler_81,
    interrupt_handler_82,
    interrupt_handler_83,
    interrupt_handler_84,
    interrupt_handler_85,
    interrupt_handler_86,
    interrupt_handler_87,
    interrupt_handler_88,
    interrupt_handler_89,
    interrupt_handler_90,
    interrupt_handler_91,
    interrupt_handler_92,
    interrupt_handler_93,
    interrupt_handler_94,
    interrupt_handler_95,
    interrupt_handler_96,
    interrupt_handler_97,
    interrupt_handler_98,
    interrupt_handler_99,
    interrupt_handler_100,
    interrupt_handler_101,
    interrupt_handler_102,
    interrupt_handler_103,
    interrupt_handler_104,
    interrupt_handler_105,
    interrupt_handler_106,
    interrupt_handler_107,
    interrupt_handler_108,
    interrupt_handler_109,
    interrupt_handler_110,
    interrupt_handler_111,
    interrupt_handler_112,
    interrupt_handler_113,
    interrupt_handler_114,
    interrupt_handler_115,
    interrupt_handler_116,
    interrupt_handler_117,
    interrupt_handler_118,
    interrupt_handler_119,
    interrupt_handler_120,
    interrupt_handler_121,
    interrupt_handler_122,
    interrupt_handler_123,
    interrupt_handler_124,
    interrupt_handler_125,
    interrupt_handler_126,
    interrupt_handler_127,
    interrupt_handler_128,
    interrupt_handler_129,
    interrupt_handler_130,
    interrupt_handler_131,
    interrupt_handler_132,
    interrupt_handler_133,
    interrupt_handler_134,
    interrupt_handler_135,
    interrupt_handler_136,
    interrupt_handler_137,
    interrupt_handler_138,
    interrupt_handler_139,
    interrupt_handler_140,
    interrupt_handler_141,
    interrupt_handler_142,
    interrupt_handler_143,
    interrupt_handler_144,
    interrupt_handler_145,
    interrupt_handler_146,
    interrupt_handler_147,
    interrupt_handler_148,
    interrupt_handler_149,
    interrupt_handler_150,
    interrupt_handler_151,
    interrupt_handler_152,
    interrupt_handler_153,
    interrupt_handler_154,
    interrupt_handler_155,
    interrupt_handler_156,
    interrupt_handler_157,
    interrupt_handler_158,
    interrupt_handler_159,
    interrupt_handler_160,
    interrupt_handler_161,
    interrupt_handler_162,
    interrupt_handler_163,
    interrupt_handler_164,
    interrupt_handler_165,
    interrupt_handler_166,
    interrupt_handler_167,
    interrupt_handler_168,
    interrupt_handler_169,
    interrupt_handler_170,
    interrupt_handler_171,
    interrupt_handler_172,
    interrupt_handler_173,
    interrupt_handler_174,
    interrupt_handler_175,
    interrupt_handler_176,
    interrupt_handler_177,
    interrupt_handler_178,
    interrupt_handler_179,
    interrupt_handler_180,
    interrupt_handler_181,
    interrupt_handler_182,
    interrupt_handler_183,
    interrupt_handler_184,
    interrupt_handler_185,
    interrupt_handler_186,
    interrupt_handler_187,
    interrupt_handler_188,
    interrupt_handler_189,
    interrupt_handler_190,
    interrupt_handler_191,
    interrupt_handler_192,
    interrupt_handler_193,
    interrupt_handler_194,
    interrupt_handler_195,
    interrupt_handler_196,
    interrupt_handler_197,
    interrupt_handler_198,
    interrupt_handler_199,
    interrupt_handler_200,
    interrupt_handler_201,
    interrupt_handler_202,
    interrupt_handler_203,
    interrupt_handler_204,
    interrupt_handler_205,
    interrupt_handler_206,
    interrupt_handler_207,
    interrupt_handler_208,
    interrupt_handler_209,
    interrupt_handler_210,
    interrupt_handler_211,
    interrupt_handler_212,
    interrupt_handler_213,
    interrupt_handler_214,
    interrupt_handler_215,
    interrupt_handler_216,
    interrupt_handler_217,
    interrupt_handler_218,
    interrupt_handler_219,
    interrupt_handler_220,
    interrupt_handler_221,
    interrupt_handler_222,
    interrupt_handler_223,
    interrupt_handler_224,
    interrupt_handler_225,
    interrupt_handler_226,
    interrupt_handler_227,
    interrupt_handler_228,
    interrupt_handler_229,
    interrupt_handler_230,
    interrupt_handler_231,
    interrupt_handler_232,
    interrupt_handler_233,
    interrupt_handler_234,
    interrupt_handler_235,
    interrupt_handler_236,
    interrupt_handler_237,
    interrupt_handler_238,
    interrupt_handler_239,
    interrupt_handler_240,
    interrupt_handler_241,
    interrupt_handler_242,
    interrupt_handler_243,
    interrupt_handler_244,
    interrupt_handler_245,
    interrupt_handler_246,
    interrupt_handler_247,
    interrupt_handler_248,
    interrupt_handler_249,
    interrupt_handler_250,
    interrupt_handler_251,
    interrupt_handler_252,
    interrupt_handler_253,
    interrupt_handler_254,
    interrupt_handler_255,
};

void init_idt() {
	idt_descriptor.limit = sizeof(idt) - 1;
	idt_descriptor.base = (uint32_t)idt;

	uint16_t selector = KCODE_SELECTOR;
	uint8_t type_attr = 0b10001110;
	uint8_t user_type_attr = 0b11101110;

	for (int i = 0; i < 256; i++) {
		uint32_t interrupt_handler_address = interrupt_handler_addresses[i];
		uint16_t offset_low = interrupt_handler_address & 0x0000FFFF;
		uint16_t offset_high = interrupt_handler_address >> 16;

		idt[i].offset_low = offset_low;
		idt[i].selector = selector;
		idt[i].zero = 0x00;
		idt[i].type_attr = type_attr;
		idt[i].offset_high = offset_high;
	}

	idt[INT_SYSCALL].type_attr = user_type_attr;

	lidt(&idt_descriptor);
}

void init_pic() {
	_outb(PIC1_DATA, 0b11111101);  // Only enable keyboard (irc 1)
	_outb(PIC2_DATA, 0b11111111);  // Don't enable any interrupts on slave pic (irc 8-15)
	sti();
}

void pic_acknowledge() {
	_outb(PIC1_COMMAND, PIC_EOI);
}